### PR TITLE
Fix TrustWalletName to match window.trustwallet

### PR DESCRIPTION
**Pull request by gregnazario**
@0xmaayan please review to ensure this is correct

### CODE REVIEW

**Comment by 0xmaayan** [comment]
LGTM

**Comment by rsrbk** [comment]
Could you please increment the version here https://github.com/trustwallet/aptos-wallet-adapter/blob/eb20b0fe7213de82cdef9f1229f1376250dae458/package.json#L3 ?

**Review by hewigovens — APPROVED** [review]

**Comment by gregnazario** [comment]
> Could you please increment the version here
> 
> https://github.com/trustwallet/aptos-wallet-adapter/blob/eb20b0fe7213de82cdef9f1229f1376250dae458/package.json#L3
> 
> ?

Of course, thanks for accepting this change :)

**Comment by gregnazario** [comment]
Updated  the version to 0.1.5 @hewigovens

**Pull request merged**
